---
- name: Install and configure Grafana Alloy
  hosts: linux
  become: yes
  vars:
    alloy_rpm_url: "https://github.com/grafana/alloy/releases/download/v1.7.5/alloy-1.7.5-1.amd64.rpm"
    alloy_config_content: |
      logging {
        level = "info"
      }

      prometheus.remote_write "mimir_host" {
        endpoint {
          url = "http://192.168.10.171:9009/api/v1/push"

          // Optional: Add authentication if needed
          // basic_auth {
          //   username = "USER"
          //   password = "PASS"
          // }
        }
      }

      prometheus.exporter.unix "localhost" {
        enable_collectors = [
          "boottime",
          "cpu",
          "cpufreq",
          "diskstats",
          "edac",
          "filesystem",
          "hwmon",
          "loadavg",
          "logind",
          "meminfo",
          "netclass",
          "netdev",
          "netstat",
          "network_route",
          "ntp",
          "os",
          "sockstat",
          "systemd",
          "thermal_zone",
          "time",
          "uname",
        ]
      }


      //scrape if unix as well
      prometheus.scrape "localhost" {
        targets    = prometheus.exporter.unix.localhost.targets
        forward_to = [prometheus.remote_write.mimir_host.receiver]
      }

      // New Loki configuration
      loki.write "loki_host" {
        endpoint {
          url = "http://192.168.10.171:3100/loki/api/v1/push"
        }
      }


      loki.source.journal "journal_logs" {
        forward_to = [loki.write.loki_host.receiver]

        labels = {
          job  = "journal",
          host = env("HOSTNAME"), // This will use the system's hostname
        }
      }


  tasks:
    - name: Download Grafana Alloy RPM
      ansible.builtin.get_url:
        url: "{{ alloy_rpm_url }}"
        dest: "/tmp/alloy-1.7.5-1.amd64.rpm"
        mode: '0644'

    - name: Install Grafana Alloy RPM
      ansible.builtin.yum:
        name: "/tmp/alloy-1.7.5-1.amd64.rpm"
        state: present

    - name: Ensure Alloy configuration directory exists (verification)
      ansible.builtin.stat:
        path: /etc/alloy
      register: alloy_dir

    - name: Create config file with specified content
      ansible.builtin.copy:
        dest: /etc/alloy/config.alloy
        content: "{{ alloy_config_content }}"
        owner: root
        group: root
        mode: '0644'

    - name: Start and enable Alloy service
      ansible.builtin.service:
        name: alloy
        state: started
        enabled: yes

    - name: Clean up RPM file
      ansible.builtin.file:
        path: "/tmp/alloy-1.7.5-1.amd64.rpm"
        state: absent
