# Do not use this configuration in production.
# It is for demonstration purposes only.
multitenancy_enabled: false

blocks_storage:
  backend: filesystem
  bucket_store:
    sync_dir: /shared-storage/mimir/tsdb-sync
  filesystem:
    dir: /shared-storage/mimir/data/tsdb
  tsdb:
    dir: /shared-storage/mimir/tsdb

compactor:
  data_dir: /shared-storage/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /var/mimir/rules

server:
  http_listen_port: 9009
  log_level: error
  grpc_listen_port: 9055

store_gateway:
  sharding_ring:
    replication_factor: 1

