# datasources.yaml
apiVersion: 1
datasources:
  - name: "loki"
    type: "loki"
    url: "http://localhost:3100"
    access: "proxy"

  - name: "mimir"
    uid: "mimir"
    type: "prometheus"
    url: "http://localhost:9009/prometheus"
    access: "proxy"
    isDefault: true
    jsonData:
      httpMethod: "POST"
      prometheusType: "Mimir"
      prometheusVersion: "2.9.1"
      tlsSkipVerify: true
      timeout: 30


  # New Infinity data source
  - name: jsondata
    type: yesoreyeram-infinity-datasource  # Plugin ID
    access: proxy
      #url: http://localhost:8080  # Replace with your API/target URL
    jsonData:
      auth_method: none  # Options: none, basic, oauth2, etc.
      tls_skip_verify: true  # For self-signed certs (optional)
    secureJsonData: {}  # Add secrets here if using auth
