# datasources.yaml
apiVersion: 1
datasources:
  - name: Loki
    type: loki
    url: http://localhost:3100  # Since Loki is in the same Pod
    access: proxy

  - name: Mimir
    type: prometheus
    url: http://localhost:9009  # Since Mimir is in the same Pod
    access: proxy
    isDefault: true


  # New Infinity data source
  - name: jsondata
    type: yesoreyeram-infinity-datasource  # Plugin ID
    access: proxy
      #url: http://localhost:8080  # Replace with your API/target URL
    jsonData:
      auth_method: none  # Options: none, basic, oauth2, etc.
      tls_skip_verify: true  # For self-signed certs (optional)
    secureJsonData: {}  # Add secrets here if using auth
