{
 "title": "VM & Docker Monitoring",
 "description": "Dashboard with details of the containers and host metrics for Raspberry Pi by Oijkn.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "step", "label": "Step", "query": "1h,30m,10m,1m,30s,10s,1s," },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   { "name": "Filters" },
   {
    "name": "fuseLogs",
    "label": "Fuse Log",
    "query": {}
   },
   {
    "name": "node",
    "label": "instance",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   },
   {
    "name": "maxmount",
    "label": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
    }
   }
  ]
 },
 "panels": [
  { "type": "library-panel-ref", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 } },
  { "title": "msnsvr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "node" },
  {
   "title": "CPU basic",
   "type": "timeseries",
   "description": "fuse.local",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"d-hub.local\",mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"d-hub.local\"}) by (cpu)))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"d-hub.local\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"d-hub.local\"}) by (cpu)))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"d-hub.local\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"d-hub.local\"}) by (cpu)))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"d-hub.local\", mode=~\".*irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"d-hub.local\"}) by (cpu)))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"d-hub.local\",  mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"d-hub.local\"}) by (cpu)))",
     "legendFormat": "Busy Others"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"d-hub.local\", mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"d-hub.local\"}) by (cpu)))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Disk used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"d-hub.local\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"d-hub.local\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Memory ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"d-hub.local\"} - node_memory_MemFree_bytes{instance=\"d-hub.local\"} - (node_memory_Cached_bytes{instance=\"d-hub.local\"} + node_memory_Buffers_bytes{instance=\"d-hub.local\"} + node_memory_SReclaimable_bytes{instance=\"d-hub.local\"})",
     "legendFormat": "RAM used"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"d-hub.local\"}",
     "legendFormat": "RAM - free"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"d-hub.local\"} + node_memory_Buffers_bytes{instance=\"d-hub.local\"} + node_memory_SReclaimable_bytes{instance=\"d-hub.local\"}",
     "legendFormat": "RAM cache + buffer"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"d-hub.local\"} - node_memory_SwapFree_bytes{instance=\"d-hub.local\"})",
     "legendFormat": "SWAP used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"d-hub.local\"}",
     "legendFormat": "RAM total"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "tx/rx by interface",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"d-hub.local\"}[$__rate_interval])*8",
     "legendFormat": "RX-{{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"d-hub.local\"}[$__rate_interval])*8",
     "legendFormat": "TX-{{device}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "system uptime",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"d-hub.local\"} - node_boot_time_seconds{instance=\"d-hub.local\"}"
    }
   ]
  },
  {
   "title": "Kernel Vers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{instance=\"d-hub.local\"}",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "Sys Load (1m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1) /  count(count(node_cpu_seconds_total{instance=\"d-hub.local\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 8, "w": 3, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5) /  count(count(node_cpu_seconds_total{instance=\"d-hub.local\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15) /  count(count(node_cpu_seconds_total{instance=\"d-hub.local\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Domain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{instance=\"d-hub.local\"}",
     "legendFormat": "{{domainname}}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "description": "Total containers running",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"d-hub.local\", image=~ \"(.)+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "r7rep",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU basic",
     "type": "timeseries",
     "description": "fuse.local",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"r7rep.thehollow\",mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"r7rep.thehollow\"}) by (cpu)))",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"r7rep.thehollow\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"r7rep.thehollow\"}) by (cpu)))",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"r7rep.thehollow\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"r7rep.thehollow\"}) by (cpu)))",
       "legendFormat": "iowait"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"r7rep.thehollow\", mode=~\".*irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"r7rep.thehollow\"}) by (cpu)))",
       "legendFormat": "irq"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"r7rep.thehollow\",  mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"r7rep.thehollow\"}) by (cpu)))",
       "legendFormat": "Busy Others"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"r7rep.thehollow\", mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"r7rep.thehollow\"}) by (cpu)))",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Disk used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"r7rep.thehollow\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"r7rep.thehollow\",device!~'rootfs'})",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Memory ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"r7rep.thehollow\"} - node_memory_MemFree_bytes{instance=\"r7rep.thehollow\"} - (node_memory_Cached_bytes{instance=\"r7rep.thehollow\"} + node_memory_Buffers_bytes{instance=\"r7rep.thehollow\"} + node_memory_SReclaimable_bytes{instance=\"r7rep.thehollow\"})",
       "legendFormat": "RAM used"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"r7rep.thehollow\"}",
       "legendFormat": "RAM - free"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"r7rep.thehollow\"} + node_memory_Buffers_bytes{instance=\"r7rep.thehollow\"} + node_memory_SReclaimable_bytes{instance=\"r7rep.thehollow\"}",
       "legendFormat": "RAM cache + buffer"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"r7rep.thehollow\"} - node_memory_SwapFree_bytes{instance=\"r7rep.thehollow\"})",
       "legendFormat": "SWAP used"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"r7rep.thehollow\"}",
       "legendFormat": "RAM total"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "tx/rx by interface",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=\"r7rep.thehollow\"}[$__rate_interval])*8",
       "legendFormat": "RX-{{device}}"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=\"r7rep.thehollow\"}[$__rate_interval])*8",
       "legendFormat": "TX-{{device}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "system uptime",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{instance=\"r7rep.thehollow\"} - node_boot_time_seconds{instance=\"r7rep.thehollow\"}"
      }
     ]
    },
    {
     "title": "Kernel Vers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 67 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_uname_info{instance=\"r7rep.thehollow\"}",
       "legendFormat": "{{release}}"
      }
     ]
    },
    {
     "title": "Sys Load (1m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (1 min average)",
     "gridPos": { "h": 8, "w": 3, "x": 16, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load1) /  count(count(node_cpu_seconds_total{instance=\"r7rep.thehollow\"}) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "Sys Load (5m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (5 min average)",
     "gridPos": { "h": 8, "w": 3, "x": 19, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load5) /  count(count(node_cpu_seconds_total{instance=\"r7rep.thehollow\"}) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "Sys Load (15m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (15 min average)",
     "gridPos": { "h": 8, "w": 2, "x": 22, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load15) /  count(count(node_cpu_seconds_total{instance=\"r7rep.thehollow\"}) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "Domain",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 71 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_uname_info{instance=\"r7rep.thehollow\"}",
       "legendFormat": "{{domainname}}"
      }
     ]
    },
    {
     "title": "Containers",
     "type": "stat",
     "description": "Total containers running",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(container_last_seen{instance=\"r7rep.thehollow\", image=~ \"(.)+\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "fuse",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU basic",
     "type": "timeseries",
     "description": "fuse.local",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"fuse.local\",mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"fuse.local\"}) by (cpu)))",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"fuse.local\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"fuse.local\"}) by (cpu)))",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"fuse.local\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"fuse.local\"}) by (cpu)))",
       "legendFormat": "iowait"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"fuse.local\", mode=~\".*irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"fuse.local\"}) by (cpu)))",
       "legendFormat": "irq"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"fuse.local\",  mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"fuse.local\"}) by (cpu)))",
       "legendFormat": "Busy Others"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"fuse.local\", mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"fuse.local\"}) by (cpu)))",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Disk used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"fuse.local\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"fuse.local\",device!~'rootfs'})",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Memory ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"fuse.local\"} - node_memory_MemFree_bytes{instance=\"fuse.local\"} - (node_memory_Cached_bytes{instance=\"fuse.local\"} + node_memory_Buffers_bytes{instance=\"fuse.local\"} + node_memory_SReclaimable_bytes{instance=\"fuse.local\"})",
       "legendFormat": "RAM used"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"fuse.local\"}",
       "legendFormat": "RAM - free"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"fuse.local\"} + node_memory_Buffers_bytes{instance=\"fuse.local\"} + node_memory_SReclaimable_bytes{instance=\"fuse.local\"}",
       "legendFormat": "RAM cache + buffer"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"fuse.local\"} - node_memory_SwapFree_bytes{instance=\"fuse.local\"})",
       "legendFormat": "SWAP used"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"fuse.local\"}",
       "legendFormat": "RAM total"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "tx/rx by interface",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=\"fuse.local\"}[$__rate_interval])*8",
       "legendFormat": "RX-{{device}}"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=\"fuse.local\"}[$__rate_interval])*8",
       "legendFormat": "TX-{{device}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "system uptime",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{instance=\"fuse.local\"} - node_boot_time_seconds{instance=\"fuse.local\"}"
      }
     ]
    },
    {
     "title": "Kernel Vers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 68 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_uname_info{instance=\"fuse.local\"}",
       "legendFormat": "{{release}}"
      }
     ]
    },
    {
     "title": "Sys Load (1m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (1 min average)",
     "gridPos": { "h": 8, "w": 3, "x": 16, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load1) /  count(count(node_cpu_seconds_total{instance=\"fuse.local\"}) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "Sys Load (5m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (5 min average)",
     "gridPos": { "h": 8, "w": 3, "x": 19, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load5) /  count(count(node_cpu_seconds_total{instance=\"fuse.local\"}) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "Sys Load (15m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (15 min average)",
     "gridPos": { "h": 8, "w": 2, "x": 22, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load15) /  count(count(node_cpu_seconds_total{instance=\"fuse.local\"}) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "Domain",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 72 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_uname_info{instance=\"fuse.local\"}",
       "legendFormat": "{{domainname}}"
      }
     ]
    },
    {
     "title": "Containers",
     "type": "stat",
     "description": "Total containers running",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(container_last_seen{instance=\"fuse.local\", image=~ \"(.)+\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "ping status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    { "title": "Response Time", "type": "library-panel-ref", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 } }
   ]
  },
  {
   "title": "fuse-application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "platformId",
     "type": "timeseries",
     "description": "output of the collector status log formatted as a chart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count_over_time({filename=\"/opt/MissionContainers/fuse/log/fabric-web/collector-status.log\"} | json platformId=\"platformId\" [$__auto])"
      }
     ]
    },
    {
     "title": "Fuse-activity",
     "type": "logs",
     "description": "tail of fuse-activity.log ",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "{filename=\"/opt/MissionContainers/fuse/log/fabric-web/fuse-activity.log\"} | json user=\"user\", systemId=\"systemId\", userId=\"userId\", platformId=\"platformId\", actionType=\"actionType\", resourceId=\"resourceId\", actionName=\"actionName\""
      }
     ]
    },
    { "title": "geos", "type": "library-panel-ref", "gridPos": { "h": 12, "w": 15, "x": 9, "y": 70 } },
    {
     "title": "Fuse Logs",
     "type": "logs",
     "description": "logs from $fuseLogs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "{filename=\"$fuseLogs\"} |= `` | logfmt"
      }
     ]
    }
   ]
  },
  {
   "title": "overview & logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    { "title": "Containers Info", "type": "library-panel-ref", "gridPos": { "h": 10, "w": 24, "x": 0, "y": 63 } }
   ]
  },
  {
   "title": "Quick CPU / Mem / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sys Load (5m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (5 min average)",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load5) /  count(count(node_cpu_seconds_total) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "CPU Busy",
     "type": "gauge",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by(instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))) * 100"
      }
     ]
    },
    {
     "title": "RAM Used",
     "type": "gauge",
     "description": "Non available RAM memory",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)"
      }
     ]
    },
    {
     "title": "RAM Total",
     "type": "stat",
     "description": "Total RAM",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "node_memory_MemTotal_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Root FS Used",
     "type": "gauge",
     "description": "Used Root FS",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
       "legendFormat": "/"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "System uptime",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds - node_boot_time_seconds",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total) by (cpu))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Containers",
     "type": "stat",
     "description": "Total containers running",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(container_last_seen{image=~ \"(.)+\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Basic CPU / Mem / Net / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Used Disk Space",
     "type": "timeseries",
     "description": "Disk space used",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{fstype!=\"rootfs\",mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{fstype!=\"rootfs\",mountpoint=\"/\"})",
       "legendFormat": "HDD"
      }
     ]
    },
    {
     "title": "Disk IO",
     "type": "timeseries",
     "description": "The number (after merges) of I/O requests completed per second for the device",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total[$__rate_interval])",
       "legendFormat": "{{device}} - reads"
      },
      {
       "expr": "- irate(node_disk_written_bytes_total[$__rate_interval])",
       "legendFormat": "{{device}} - writes"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by(instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[$__rate_interval])))) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
       "legendFormat": "RAM"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$__rate_interval])) by (id)",
       "legendFormat": "received {{device}}"
      },
      {
       "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$__rate_interval])) by (id)",
       "legendFormat": "sent {{device}} "
      }
     ]
    },
    {
     "title": "fuse activity table",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
     "targets": [
      {
       "expr": "{filename=\"/opt/MissionContainers/fuse/log/fabric-web/fuse-activity.log\"} | json"
      }
     ]
    }
   ]
  },
  { "title": "Docker Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$__rate_interval])) by (name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RSS Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name!=\"\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "I/O Rx FS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without (dc,from,id,csv) (irate(container_fs_writes_bytes_total{image!=\"\",device!~\"/dev/dm.*\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "I/O Tx FS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without (dc,from,id,csv) (irate(container_fs_reads_bytes_total{image!=\"\",device!~\"/dev/dm.*\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "type": "library-panel-ref", "gridPos": { "h": 10, "w": 24, "x": 0, "y": 111 } }
 ]
}