{
 "title": "Windows Server Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(windows_cs_hostname{job!=\"Linux\", job!=\"Harvest\"},instance)"
    }
   },
   {
    "name": "ServiceDisplayName",
    "label": "Service Display Name",
    "query": {
     "query": "label_values(windows_service_info{instance=~\"$Hostname\"},display_name)"
    }
   },
   {
    "name": "ServiceName",
    "label": "Service Name",
    "query": {
     "query": "label_values(windows_service_info{display_name=~\"$ServiceDisplayName\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ping",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up {instance=~\"$Hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\", instance=~\"$Hostname\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - windows_os_physical_memory_free_bytes{instance=~\"$Hostname\"} / windows_cs_physical_memory_bytes{instance=~\"$Hostname\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Space Used",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-(windows_logical_disk_free_bytes{volume!~\"HarddiskVolume.*\", instance=~\"$Hostname\"} / windows_logical_disk_size_bytes{volume!~\"HarddiskVolume.*\", instance=~\"$Hostname\"})*100",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Service",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_service_state{instance=~\"$Hostname\", name=~\"$ServiceName\", state=~\"running|paused|stopped|unknown\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-windows_system_system_up_time {instance=\"$Hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "GHZ" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (windows_cpu_core_frequency_mhz{instance=~\"$Hostname\"}) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " windows_os_physical_memory_free_bytes{instance=~\"$Hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Space Free",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{volume!~\"HarddiskVolume.*\", instance=~\"$Hostname\"}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "targets": [
    {
     "expr": "windows_service_state{instance=~\"$Hostname\", name=~\"$ServiceName\", state=~\"running|paused|stopped|unknown\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Used In Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\", instance=~\"$Hostname\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Memory Used In Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - windows_os_physical_memory_free_bytes{instance=~\"$Hostname\"} / windows_cs_physical_memory_bytes{instance=~\"$Hostname\"} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Free In Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": " windows_os_physical_memory_free_bytes{instance=~\"$Hostname\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Storage Used", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Storage Free In Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{volume!~\"HarddiskVolume.*\", instance=~\"$Hostname\"}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Storage Used In Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100-(windows_logical_disk_free_bytes{volume!~\"HarddiskVolume.*\", instance=~\"$Hostname\"} / windows_logical_disk_size_bytes{volume!~\"HarddiskVolume.*\", instance=~\"$Hostname\"})*100",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 61 },
   "options": {
    "content": "<div style=\"text-align: right;\">\n    <a href=\"https://furycode.org/\">\n        <img src=\"https://furycode.org/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fflame.26b9b203.png&w=640&q=75\" height=\"80\" alt=\"Flame\">\n    </a>\n</div>"
   }
  }
 ]
}