{
 "title": "Windows fleet overview",
 "description": "Overview of youre windows fleet",
 "tags": [ "windows-exporter-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(windows_os_info{job=~\"integrations/windows_exporter\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(windows_os_info{job=~\"integrations/windows_exporter\",job=~\"$job\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Metrics",
   "type": "stat",
   "description": "Shows if metrics are being received for the selected time range.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector(1) and on() ((count(up{job=~\"integrations/windows.*\"} == 1) > 0) and (absent(absent(windows_cs_hostname{job=~\"integrations/windows.*\"})))) or vector(0) and on() ((count(up{job=~\"integrations/windows.*\"}) > 0) and (absent(windows_cs_hostname{job=~\"integrations/windows.*\"})))\n"
    }
   ]
  },
  {
   "title": "Latest metrics received",
   "type": "stat",
   "description": "Shows the timestamp of the latest metrics received for this integration in the last 24 hours.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector(1) and on() ((count(up{job=~\"integrations/windows.*\"} == 1) > 0) and (absent(absent(windows_cs_hostname{job=~\"integrations/windows.*\"})))) or vector(0) and on() ((count(up{job=~\"integrations/windows.*\"}) > 0) and (absent(windows_cs_hostname{job=~\"integrations/windows.*\"})))\n"
    }
   ]
  },
  {
   "title": "Integration version",
   "type": "stat",
   "description": "Shows the installed version of this integration.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "Fleet overview",
   "type": "table",
   "description": "All Windows instances' perfomance at a glance.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "windows_os_info{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "time() - windows_system_system_up_time{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "windows_cs_logical_processors{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "100 - (avg without (mode,core) (rate(windows_cpu_time_total{mode=\"idle\", job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*100))",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory total"
    },
    {
     "expr": "100 - windows_os_physical_memory_free_bytes{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"} / windows_cs_physical_memory_bytes{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"} * 100"
    },
    {
     "expr": "windows_logical_disk_size_bytes{volume=\"C:\", job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "100 - windows_logical_disk_free_bytes{volume=\"C:\", job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}/windows_logical_disk_size_bytes{volume=\"C:\", job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}*100"
    },
    {
     "expr": "count by (instance) (max_over_time(ALERTS{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\", alertstate=\"firing\", severity=\"critical\"}[1m])) * group by (instance) (windows_os_info{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"})"
    },
    {
     "expr": "count by (instance) (max_over_time(ALERTS{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\", alertstate=\"firing\", severity=\"warning\"}[1m])) * group by (instance) (windows_os_info{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Top 25",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(25,100 - (avg without (mode,core) (rate(windows_cpu_time_total{mode=\"idle\", job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*100)))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg(100 - (avg without (mode,core) (rate(windows_cpu_time_total{mode=\"idle\", job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*100)))",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Top 25",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(25,100 - windows_os_physical_memory_free_bytes{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"} / windows_cs_physical_memory_bytes{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"} * 100)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg(100 - windows_os_physical_memory_free_bytes{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"} / windows_cs_physical_memory_bytes{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"} * 100)",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "description": "Top 25",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(25,(1-clamp_max(irate(windows_logical_disk_idle_seconds_total{volume!~\"HarddiskVolume.*\", job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]),1)) * 100)",
     "legendFormat": "{{instance}}: {{volume}}"
    },
    {
     "expr": "avg((1-clamp_max(irate(windows_logical_disk_idle_seconds_total{volume!~\"HarddiskVolume.*\", job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]),1)) * 100)",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "timeseries",
   "description": "Top 25",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(25,100 - windows_logical_disk_free_bytes{volume!~\"HarddiskVolume.*\", job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}/windows_logical_disk_size_bytes{volume!~\"HarddiskVolume.*\", job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}*100)",
     "legendFormat": "{{instance}}: {{volume}}"
    },
    {
     "expr": "avg(100 - windows_logical_disk_free_bytes{volume!~\"HarddiskVolume.*\", job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}/windows_logical_disk_size_bytes{volume!~\"HarddiskVolume.*\", job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}*100)",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Network errors and dropped packets",
   "type": "timeseries",
   "description": "**Network errors**:\n\nNetwork errors refer to issues that occur during the transmission of data across a network. \n\nThese errors can result from various factors, including physical issues, jitter, collisions, noise and interference.\n\nMonitoring network errors is essential for diagnosing and resolving issues, as they can indicate problems with network hardware or environmental factors affecting network quality.\n\n**Dropped packets**:\n\nDropped packets occur when data packets traveling through a network are intentionally discarded or lost due to congestion, resource limitations, or network configuration issues. \n\nCommon causes include network congestion, buffer overflows, QoS settings, and network errors, as corrupted or incomplete packets may be discarded by receiving devices.\n\nDropped packets can impact network performance and lead to issues such as degraded voice or video quality in real-time applications.\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(irate(windows_net_packets_outbound_errors_total{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))>0.5",
     "legendFormat": "{{instance}}: {{ nic }} transmitted"
    },
    {
     "expr": "(irate(windows_net_packets_received_errors_total{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))>0.5",
     "legendFormat": "{{instance}}: {{ nic }} received"
    },
    {
     "expr": "(irate(windows_net_packets_received_unknown_total{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))>0.5",
     "legendFormat": "{{instance}}: {{ nic }} received (unknown)"
    },
    {
     "expr": "(irate(windows_net_packets_outbound_discarded_total{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))>0.5",
     "legendFormat": "{{instance}}: {{ nic }} transmitted packets dropped"
    },
    {
     "expr": "(irate(windows_net_packets_received_discarded_total{job=~\"integrations/windows_exporter\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))>0.5",
     "legendFormat": "{{instance}}: {{ nic }} received packets dropped"
    }
   ]
  }
 ]
}