{
 "title": "Core Hub metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "pipelineName", "label": "Pipelines", "query": { "query": "label_values(pipelineName)" } },
   {
    "name": "entityName",
    "label": "Entities",
    "query": {
     "query": "label_values({pipelineName=~\"$pipelineName\"},entityName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "End to end time",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 22, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gluesync_last_end_to_end_time{pipelineName=~\"$pipelineName\", entityName=~\"$entityName\"}",
     "legendFormat": " {{entityName}}"
    }
   ]
  },
  {
   "title": "JVM Used Memory Bytes Composition",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 22, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_buffer_memory_used_bytes", "legendFormat": "{{label_name}}" },
    { "expr": "jvm_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Core Hub CPU Usage",
   "type": "stat",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "gluesync_processor_cpu_load", "legendFormat": "__auto" },
    { "expr": "gluesync_system_cpu_load", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Row count transferred (rate) vs Core Hub CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 11, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(gluesync_total_count{pipelineName=~\"$pipelineName\", entityName=~\"$entityName\"}[$__rate_interval])",
     "legendFormat": "{{pipelineName}}(id {{pipelineId}}) - {{entityName}}(id {{entityId}})"
    },
    { "expr": "gluesync_system_cpu_load", "legendFormat": "Gluesync CPU Load" }
   ]
  },
  {
   "title": "JVM  RAM Used bytes",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gluesync_average_size_bytes{pipelineName=\"$pipelineName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gluesync_total_size_bytes{pipelineName=\"$pipelineName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_memory_used_bytes{job=\"gluesync-core-hub\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 11, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(gluesync_last_write_time{pipelineName=~\"$pipelineName\", entityName=~\"$entityName\"}[$__rate_interval])",
     "legendFormat": "{{pipelineName}}(id {{pipelineId}}) - {{entityName}}(id {{entityId}})"
    }
   ]
  },
  {
   "title": "Data Transfer per time (rate)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(gluesync_total_size_bytes{pipelineName=~\"$pipelineName\", entityName=~\"$entityName\"}[$__rate_interval])",
     "legendFormat": "{{pipelineName}}(id {{pipelineId}}) - {{entityName}}(id {{entityId}})"
    }
   ]
  },
  {
   "title": "Storage time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 11, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(gluesync_last_storage_time{pipelineName=~\"$pipelineName\", entityName=~\"$entityName\"}[$__rate_interval])",
     "legendFormat": "{{pipelineName}}(id {{pipelineId}}) - {{entityName}}(id {{entityId}})"
    }
   ]
  },
  {
   "title": "Read time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(gluesync_last_read_time{pipelineName=~\"$pipelineName\", entityName=~\"$entityName\"}[$__rate_interval])",
     "legendFormat": "{{pipelineName}}(id {{pipelineId}}) - {{entityName}}(id {{entityId}})"
    }
   ]
  },
  {
   "title": "Moving average transaction message row count",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 11, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gluesync_sma_count{pipelineName=~\"$pipelineName\", entityName=~\"$entityName\"}",
     "legendFormat": "{{pipelineName}}(id {{pipelineId}}) - {{entityName}}(id {{entityId}})"
    }
   ]
  },
  {
   "title": "End to end time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(gluesync_last_end_to_end_time{pipelineName=~\"$pipelineName\", entityName=~\"$entityName\"}[$__rate_interval])",
     "legendFormat": "{{pipelineName}}(id {{pipelineId}}) - {{entityName}}(id {{entityId}})"
    }
   ]
  },
  {
   "title": "Moving average transferred data size",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 11, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gluesync_sma_size_bytes{pipelineName=~\"$pipelineName\", entityName=~\"$entityName\"}",
     "legendFormat": "{{pipelineName}}(id {{pipelineId}}) - {{entityName}}(id {{entityId}})"
    }
   ]
  }
 ]
}