{
 "title": "OGS - Main Status",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "server",
    "query": {
     "query": "query_result(group by (instance) ({__name__=~\"node_cpu_seconds_total|windows_cpu_time_total\"}))"
    }
   },
   { "name": "ansible_ping", "label": "ansible_ping", "query": { "query": "" } },
   { "name": "now", "label": "now", "query": { "query": "query_result(time())" } },
   {
    "name": "linuxvolumes",
    "label": "linuxvolumes",
    "query": {
     "query": "label_values(node_filesystem_size_bytes{mountpoint!~\"^/(run|sys|proc|dev|boot/efi|boot)(/|$)\", fstype!=\"tmpfs\"},mountpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ansible Pings",
   "type": "table",
   "description": "Checks authentication and connection via playbook every 5 minutes",
   "gridPos": { "h": 22, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "last_over_time({__name__=~\"node_up\"}[5m])"
    },
    {
     "expr": "floor(time() - last_over_time({__name__=~\"node_last_up_seconds\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(system_patch_version, \"exported_hostname\", \"$1\", \"hostname\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services and Disk usage",
   "type": "grafana-polystat-panel",
   "description": "monitored services and disk usage",
   "gridPos": { "h": 22, "w": 3, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "windows_service_state{job=\"integrations/windows\", state=\"running\", instance=~\"DC1|DC2\", name=~\"dns|kdc|ntds|winrm\"}",
     "legendFormat": "{{instance}} - {{name}}"
    },
    {
     "expr": "absent(up{instance=~\"DC1|DC2\"}) == bool 0",
     "legendFormat": "DC-down"
    },
    {
     "expr": "windows_service_state{job=\"integrations/windows\", state=\"running\", instance=~\"VMFWS3|VMFWS4|VMFWS5\", name=~\"winrm\"}",
     "legendFormat": "{{instance}} - {{name}}"
    },
    {
     "expr": "absent(up{instance=~\"VMFWS3|VMFWS4|VMFWS5\"}) == bool 0",
     "legendFormat": "VMFWS-down"
    },
    {
     "expr": "windows_service_state{job=\"integrations/windows\", state=\"running\", instance=~\"vsql\", name=~\"winrm|mssqlserver\"}",
     "legendFormat": "{{instance}} - {{name}}"
    },
    {
     "expr": "absent(up{instance=~\"vsql\"}) == bool 0",
     "legendFormat": "VSQL-down"
    },
    {
     "expr": "windows_service_state{job=\"integrations/windows\", state=\"running\", instance=~\"viewcon\", name=~\"winrm|vgauthservice|wsbroker\"}",
     "legendFormat": "{{instance}} - {{name}}"
    },
    {
     "expr": "absent(up{instance=~\"viewcon\"}) == bool 0",
     "legendFormat": "VIEWCON-down"
    },
    {
     "expr": "windows_service_state{job=\"integrations/windows\", state=\"running\", instance=~\"GPED-SVR-V1\", name=~\"winrm|mysql57\"}",
     "legendFormat": "{{instance}} - {{name}}"
    },
    {
     "expr": "absent(up{instance=~\"GPED-SVR-V1\"}) == bool 0",
     "legendFormat": "VADER-down"
    },
    {
     "expr": "windows_service_state{job=\"integrations/windows\", state=\"running\", instance=~\"OGS-VANTAGE\", name=~\"winrm|vantage|mysql\"}",
     "legendFormat": "{{instance}} - {{name}}"
    },
    {
     "expr": "absent(up{instance=~\"OGS-VANTAGE\"}) == bool 0",
     "legendFormat": "VANTAGE-down"
    },
    {
     "expr": "windows_service_state{job=\"integrations/windows\", state=\"running\", instance=~\"FMV\", name=~\"winrm|openfire|dhcpserver\"}",
     "legendFormat": "{{instance}} - {{name}}"
    },
    {
     "expr": "absent(up{instance=~\"FMV\"}) == bool 0",
     "legendFormat": "FMV-down"
    },
    {
     "expr": "windows_service_state{job=\"integrations/windows\", state=\"running\", instance=~\"ENTERPRISE-CA\", name=~\"winrm|certsvc\"}",
     "legendFormat": "{{instance}} - {{name}}"
    },
    {
     "expr": "absent(up{instance=~\"ENTERPRISE-CA\"}) == bool 0",
     "legendFormat": "ENT-CA-down"
    },
    {
     "expr": "windows_service_state{job=\"integrations/windows\", state=\"running\", instance=~\"ANS-SYSCON\", name=~\"winrm\"}",
     "legendFormat": "{{instance}} - {{name}}"
    },
    {
     "expr": "absent(up{instance=~\"ANS-SYSCON\"}) == bool 0",
     "legendFormat": "ANS-SYSCON-down"
    },
    {
     "expr": "windows_service_state{job=\"integrations/windows\", instance=~\"AESS\", name=~\"winrm|mcafeeapachesrv|mcafeeeventparsersrv|mcafeetomcatsrv5100|mssql\\\\$essepo|sqltelemetry\\\\$essepo\", state=\"running\"}",
     "legendFormat": "{{instance}} - {{name}}"
    },
    {
     "expr": "absent(up{instance=~\"AESS\"}) == bool 0",
     "legendFormat": "AESS-down"
    },
    {
     "expr": "node_systemd_unit_state{instance=~\"vnia1.j114.army.mil|vnia2.j114.army.mil|vnia4.j114.army.mil|netcfgsvr1.j114.army.mil|controller1|grafana\", name=~\"frr.service|sshd.service|pimd.service|jCon.service\", state=\"active\"}",
     "legendFormat": "{{instance}} - {{name}}"
    },
    {
     "expr": "absent(up{instance=~\"vnia1.j114.army.mil|vnia2.j114.army.mil\"}) == bool 0",
     "legendFormat": "VNIA1-down"
    },
    {
     "expr": "absent(up{instance=~\"vnia2.j114.army.mil\"}) == bool 0",
     "legendFormat": "VNIA2-down"
    },
    {
     "expr": "absent(up{instance=~\"vnia4.j114.army.mil\"}) == bool 0",
     "legendFormat": "VNIA4-down"
    },
    {
     "expr": "absent(up{instance=~\"controller1\"}) == bool 0",
     "legendFormat": "AAP-down"
    },
    {
     "expr": "absent(up{instance=~\"grafana\"}) == bool 0",
     "legendFormat": "GRAFANA-down"
    },
    {
     "expr": "100 * (1 - (node_filesystem_avail_bytes{mountpoint!~'^(/run|/boot|/boot/efi|/sys|/proc|/dev|/snap)(/|$)',fstype!='tmpfs'} / node_filesystem_size_bytes{mountpoint!~'^(/run|/boot|/boot/efi|/sys|/proc|/dev|/snap)(/|$)',fstype!='tmpfs'}))",
     "legendFormat": "{{instance}} - {{mountpoint}}"
    },
    {
     "expr": "clamp_min(100 * (1 - (windows_logical_disk_free_bytes{job=\"integrations/windows\", volume=~\"[A-Z]:\"} / windows_logical_disk_size_bytes{job=\"integrations/windows\", volume=~\"[A-Z]:\"})), 1.1)",
     "legendFormat": "{{instance}} - {{volume}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Host",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(instance) (rate(node_cpu_seconds_total{mode!=\"idle\", instance=~\"$server\"}[5m])) * 100",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "avg by(instance) (rate(windows_cpu_time_total{mode!=\"idle\", instance=~\"$server\"}[5m])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}